name: deploy github pages
on:
    push:
        branches:
            - dev
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 1. Checkout
              uses: actions/checkout@master
            - name: Submodule Checkout
              uses: jwsi/submodule-checkout@v1

            - name: 2. setup nodejs...

              uses: actions/setup-node@v2
              with:
                node-version: '14'

            - name: 3. build
              run: |
                  npm i
                  npm run build

            - name: 4. deploy github pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
                  BRANCH: main
                  FOLDER: hexo-theme
